language: cpp

# `sudo: required` is specified only in order to use a machine with more RAM, allowing more
# compilation jobs in parallel.
dist: trusty
sudo: required
cache: ccache

matrix:
  include:
    - os: linux
      env: PY_VER=3.6 REAKTORO_USE_OPENLIBM=1

    - os: linux
      env: PY_VER=3.7

    - os: osx
      osx_image: xcode11
      env: PY_VER=3.6 REAKTORO_USE_OPENLIBM=1

    - os: osx
      osx_image: xcode11
      env: PY_VER=3.7

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64; fi
  - wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-$OS.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export CONDA_BIN=$HOME/miniconda/bin
  - export CONDA=$CONDA_BIN/conda
  - $CONDA config --system --set always_yes yes --set changeps1 no
  - $CONDA config --system --append channels conda-forge
  - $CONDA install -n base conda-devenv
  # Number of compilation jobs is limited by machine RAM. Too many and GCC will die with
  # "internal compiler error"
  - export "NUMBER_OF_COMPILATION_JOBS=4"

install:
  - $CONDA devenv
  - source $CONDA_BIN/activate reaktoro

script:
  - export "CFLAGS=-I$CONDA_PREFIX/include $CFLAGS"
  - export "CXXFLAGS=-I$CONDA_PREFIX/include $CXXFLAGS"
  - echo -e "\n\nCurrent compiler configuration:\nCXX=$CXX\nCC=$CC\nCFLAGS=$CFLAGS\nCXXFLAGS=$CXXFLAGS"
  - echo -e "\nCurrent packages:"
  - $CONDA list
  - inv -e compile -n $NUMBER_OF_COMPILATION_JOBS
  - python ci/check_compiled_files.py
  - pytest -n auto -ra -vv .
